version: '3.7'

services:
  users_app:
    build:
      context: ./users
    container_name: users_app
    image: 691179146525.dkr.ecr.us-east-1.amazonaws.com/users_app:latest
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL={DATABASE_URL}

  nginx:
    container_name: nginx
    depends_on:
      - users_app
    image: 691179146525.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
    ports:
      - "80:80"
    build: 
      context: ./nginx